name: Github Actions Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  
jobs: 
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Print out general information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch name: ${{github.ref}}"
      
      - uses: actions/checkout@v3.3.0
      
      - name: List files in the repository
        run: |
          echo "all files in the repo are ${{github.repository}}:"
          tree
        

        

      

    
